include:
  - ./compose.infrastructure.yaml
  - ./compose.services.yaml
  - ./compose.web.yarml

networks:
  monorepo-network:
    driver: bridge

volumes:
  rift_hub_pg:
  rabbitmq_data:
  redis_data:
