services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - rift_hub_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monorepo-network
    restart: unless-stopped

  profile-service:
    build:
      context: ../../apps/profile-service
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${PROFILE_DB_NAME}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PROFILE_DB_NAME}
      HOST: ${PROFILE_HOST}
      PORT: ${PROFILE_PORT}
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${PROFILE_PORT}:${PROFILE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://${PROFILE_HOST}:${PROFILE_PORT}/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monorepo-network
    restart: unless-stopped

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
      args:
        WEB_PORT: ${WEB_PORT}
    environment:
      WEB_PORT: ${WEB_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - profile-service
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://${WEB_HOST}:${WEB_PORT}/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monorepo-network
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    environment:
      WEB_PORT: ${WEB_PORT}
      PROFILE_PORT: ${PROFILE_PORT}
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    command: >
      /bin/sh -c "envsubst '$$WEB_PORT $$PROFILE_PORT $$NGINX_PORT $$NGINX_HOST'
      < /etc/nginx/conf.d/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    depends_on:
      web:
        condition: service_healthy
      profile-service:
        condition: service_healthy
    networks:
      - monorepo-network
    restart: unless-stopped

networks:
  monorepo-network:
    driver: bridge

volumes:
  rift_hub_pg:
