services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - rift_hub_pg:/var/lib/postgresql/data

  profile-service:
    image: apps-profile-service:latest
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PROFILE_DB_NAME}
      HOST: ${PROFILE_HOST}
      PORT: ${PROFILE_PORT}
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${PROFILE_PORT}:3000"
    depends_on:
      - postgres

volumes:
  rift_hub_pg:
