export enum AuthErrorCodes {
  INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  USER_ALREADY_EXIST = "USER_ALREADY_EXIST",

  INVALID_OTP_CODE = "INVALID_OTP_CODE",
  OTP_CODE_EXPIRED = "OTP_CODE_EXPIRED",
  INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
  OTP_RESEND_TOO_SOON = "OTP_RESEND_TOO_SOON",
}
